---
output: 
    html_document:
        css: styles.css
---
<br>

<article>
<h3><a href="my_first_api.html">Making a dummy website using an API</a></h3>
<span><i class="fa fa-calendar"></i> 2019-11-01</span>
<a class="btn btn-outline-primary btn-sm" href="my_first_api.html">Read More</a>
</article>

<article>
<h3><a href="extracting_data_from_pdf.html">Extracting Data From Web-Based PDF Files</a></h3>
<span><i class="fa fa-calendar"></i> 2019-05-06</span>
<p>Many times there are multiple data sets that we’d like to download from a website. Sometimes we are fortunate enough that the data is stored in multiple csv files within a zipped folder or under a common link. But what if the data is not centrally stored in a single zipped file or is not in csv format?...</p>
<a class="btn btn-outline-primary btn-sm" href="extracting_data_from_pdf.html">Read More</a>
</article>

<article>
<h3><a href="hpv.html">Human Papillomavirus Vaccine (HPV) Completion Rate</a></h3>
<span><i class="fa fa-calendar"></i> 2018-11-21</span>
<p>This post attempts to analyze the characteristics of non-pregnant females between the ages of 11 and 26 who started the three-shot sequence of the HPV vaccine and subsequently completed the sequence within 12 months. The data used was collected by the Johns Hopkins Institutional Review Board between January 1, 2007 and June 30, 2008...</p>
<a class="btn btn-outline-primary btn-sm" href="hpv.html">Read More</a>
</article>


<article>
<h3><a href="anova.html">One-Way Analysis of Variance</a></h3>
<span><i class="fa fa-calendar"></i> 2018-02-11</span>
<p>When there are multiple means to compare it is incorrect to use multiple two independent sample t-tests as this increases the chances of making a Type I error. The One-Way Analysis of Variance (ANOVA), also known as a completely randomized design, is used to determine whether there is a statistically significant difference between the means of two or more independent groups, i.e., the difference in means between groups is too large to be the product of random selection...</p>
<a class="btn btn-outline-primary btn-sm" href="anova.html">Read More</a>
</article>

<article>
<h3><a href="FEVRegression.html">Regression Analysis of Forced Expiratory Volume</a></h3>
<span><i class="fa fa-calendar"></i> 2018-01-23</span>
<p>Forced expiratory volume (FEV) is the amount of air a person can exhale during a forced breath. The amount of air exhaled may be measured during the first (FEV$_1$), second (FEV$_2$) or third (FEV$_3$) seconds of the forced breath. FEV is measured during a pulmonary function test by a diagnostic device called a spirometer, which records the amount of air that passes through the body as the person exhales...</p>
<a class="btn btn-outline-primary btn-sm" href="FEVRegression.html">Read More</a>
</article>

<article>
<h3><a href="Poisson.html">An Application of Poisson Distribution</a></h3>
<span><i class="fa fa-calendar"></i> 2017-12-15</span>
<p>A local testing center, accommodates a bi-weekly computerized psychology test. The test occurs on Monday and Friday from 7:30 pm to 9:30 pm. On reviewing the data for the last 25 Fridays, on which the test was available, the manager noticed that the number of people that took the test was drastically lower than the number of people that took the test on Monday of the same week...</p>
<a class="btn btn-outline-primary btn-sm" href="Poisson.html">Read More</a>
</article>

