<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Analysis of Human Papillomavirus Vaccine (HPV) Completion Rate</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Laurence James-Woodley</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="blog.html">BLOG</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ljwoodley">
    <span class="fa fa-github fa-2x"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/laurencejwoodley/">
    <span class="fa fa-linkedin fa-2x"></span>
     
  </a>
</li>
<li>
  <a href="mailto:laurencejwoodley@gmail.com">
    <span class="fas fa fas fa-envelope fa-2x"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Analysis of Human Papillomavirus Vaccine (HPV) Completion Rate</h1>

</div>


<div class="figure">
<img src="https://www.washingtonpost.com/resizer/qHRadEF0D0_bZIiowKGvcQSClmU=/1400x0/arc-anglerfish-washpost-prod-thelily-washpost.s3.amazonaws.com/public/LNIPS5FXOJEDBLN4SMBMGZGDEM.gif" />

</div>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>This post attempts to analyze the characteristics of non-pregnant females between the ages of 11 and 26 who started the three-shot sequence of the HPV vaccine and subsequently completed the sequence within 12 months. The data used was collected by the Johns Hopkins Institutional Review Board between January 1, 2007 and June 30, 2008. This sample consists of 1,413 patients of which 469 (33.2%) completed the vaccine within 12 months. The remaining patients either did not complete the sequence or took more than twelve months to complete the sequence. The variables included are <code>agegroup</code> (11-17, 18-26), <code>race</code> (white, minority), <code>medassist</code> (patient had medical insurance, patient did not have medical insurance),<code>locationtype</code> (suburban, urban), <code>practicetype</code> (family practice, ob-gyn, pediatric) and <code>completed</code> (completed vaccine within 12 months, did not complete vaccine within 12 months). All analyses was conducted at the 5% significance level.</p>
</div>
<div id="preliminary-analysis" class="section level3">
<h3>Preliminary Analysis</h3>
<p>Let’s first load and format the data. We’ll then create a bar graph and do a proportion test for each predictor to determine how it is associated with completion rate.</p>
<pre class="r"><code>#import and format data. 
df &lt;- read_csv(&quot;projects_data/hpv_data.csv&quot;) %&gt;%
  #convert all variable to lowercase
  rename_all(tolower) %&gt;% 
  #give variable categories proper names
  mutate(race = case_when(race == 0 ~ &#39;white&#39;,
                          TRUE ~  &#39;minority&#39;),
         completed = case_when(completed  == 0 ~ &#39;no&#39;,
                               TRUE ~ &#39;yes&#39;),
         locationtype = case_when(locationtype == 0 ~ &#39;suburban&#39;,
                                  TRUE ~ &#39;urban&#39;),
         practicetype = case_when(practicetype == 0 ~ &#39;pediatric&#39;,
                                  practicetype == 1 ~ &#39;family practice&#39;,
                                  TRUE ~ &#39;ob-gyn&#39;),
         medassist = case_when(medassist == 0 ~ &#39;insurance&#39;,
                               TRUE ~ &#39;no insurance&#39;),
         agegroup = case_when(agegroup == 0 ~ &#39;11-17&#39;,
                              TRUE ~ &#39;18-26&#39;)) %&gt;% 
  #convert all variables to factors
  mutate_all(as.factor) %&gt;% 
  #put dependent variable first in data frame
  select(completed, everything())
 
#Function to visualize completion rates. Takes a predictor as input.
create_bargraph &lt;- function(var_name){
  df %&gt;% 
    group_by(!!enquo(var_name), completed) %&gt;% 
    summarise(count = n()) %&gt;% 
    mutate(percentage = round(count/sum(count), 2)) %&gt;% 
  ggplot(., aes(x = !!enquo(var_name), y = percentage, fill = completed))+
    geom_col()+
    scale_y_continuous(labels = percent)+
    geom_text(aes(label = paste0(round(percentage*100),&quot;%\n&quot;, &#39;(&#39;,count,&#39;)&#39;)), position = position_stack(vjust = 0.5))+
    scale_fill_brewer(palette = &quot;Dark2&quot;)+
    labs(y = &quot;HPV vaccine completion rates\n (n)&quot;)
    
}

#function to create data  frame for proprotion test.
#Takes predictor as input
prop_data &lt;- function(var_name){
  df %&gt;% 
    group_by(!!enquo(var_name), completed) %&gt;%
    summarise(count = n()) %&gt;% 
    spread(completed, count) %&gt;% 
    mutate(total = no + yes) %&gt;% 
    rename(&quot;group&quot; = !!enquo(var_name), &quot;success&quot; = &quot;yes&quot;)
  }

#function for two-sample proportion tests. Takes prop_data as input 
#this was mainly created to do a proportion test on 
#practicetype as it contains three categories
prop_test &lt;- function(x){
  for (i in 1:(nrow(x)-1)){
    for (j in 2:nrow(x)){
      if (i != j &amp; i &lt; j ){
        cat(&quot;--------------------------------------------------------------------\n&quot;)
        cat(paste(&#39;Proportion test for:&#39;, x$group[i],&quot;vs&quot;, x$group[j]))
        print(prop.test(c(x$success[i], x$success[j]), c(x$total[i], x$total[j])))
      }
    }
  }
}

create_output &lt;- function(x){
create_bargraph(!!sym(x)) %&gt;% 
  print()
prop_data(!!sym(x)) %&gt;% 
  prop_test()
}

vars &lt;- c(&#39;agegroup&#39;,&#39;locationtype&#39;,&#39;medassist&#39;,&#39;race&#39;,&#39;practicetype&#39;)
for (i in seq_along(vars)){
  create_output(vars[i])
}</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## --------------------------------------------------------------------
## Proportion test for: 11-17 vs 18-26
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 2.4403, df = 1, p-value = 0.1183
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.009933481  0.091045536
## sample estimates:
##    prop 1    prop 2 
## 0.3523538 0.3117978</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-1-2.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## --------------------------------------------------------------------
## Proportion test for: suburban vs urban
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 17.872, df = 1, p-value = 2.363e-05
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.06324615 0.16736652
## sample estimates:
##    prop 1    prop 2 
## 0.3686397 0.2533333</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-1-3.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## --------------------------------------------------------------------
## Proportion test for: insurance vs no insurance
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 26.063, df = 1, p-value = 3.305e-07
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.1066176 0.2209747
## sample estimates:
##    prop 1    prop 2 
## 0.3637961 0.2000000</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-1-4.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## --------------------------------------------------------------------
## Proportion test for: minority vs white
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 17.063, df = 1, p-value = 3.615e-05
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.15508657 -0.05487468
## sample estimates:
##    prop 1    prop 2 
## 0.2775330 0.3825137</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-1-5.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## --------------------------------------------------------------------
## Proportion test for: family practice vs ob-gyn
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 6.8576, df = 1, p-value = 0.008827
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.15115096 -0.02224851
## sample estimates:
##    prop 1    prop 2 
## 0.2904110 0.3771107 
## 
## --------------------------------------------------------------------
## Proportion test for: family practice vs pediatric
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 0.4798, df = 1, p-value = 0.4885
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.08795107  0.03964677
## sample estimates:
##    prop 1    prop 2 
## 0.2904110 0.3145631 
## 
## --------------------------------------------------------------------
## Proportion test for: ob-gyn vs pediatric
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 4.254, df = 1, p-value = 0.03916
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.003182059 0.121913116
## sample estimates:
##    prop 1    prop 2 
## 0.3771107 0.3145631</code></pre>
<p>Based on the results of the two sample test of equality of proportions we see that there is no significant difference in the completion rates between the two age groups (p &gt; 0.05) and there is also no significant difference in the completion rates between patients that attended pediatric clinics and family practice clinics (p &gt; 0.05). However, there is a significant difference between the other comparisons as all p-values were below 0.05.</p>
<p>For instance, we can conclude that the population proportion of completion rates differ for patients that attended suburban clinics and urban clinics. The sample values (<span class="math inline">\(\hat{p}_1\)</span> = 0.37, <span class="math inline">\(\hat{p}_2\)</span> = 0.25) suggests that the population proportion is higher for patients that attended suburban clinics. Additionally, if we were to collect 100 different samples from the population of women aged 11-26 who enrolled in the anti-HPV vaccination regimen the true proportion of completion rates would be between 6.3% and 16.7% higher for patients that attended suburban clinics compared to urban clinics approximately 95 out of 100 times.</p>
<p>Wow, statistics is not as confusing as everyone says it is 😄! We conducted a simple hypothesis test which showed that there was no significant difference in the completion rate between the two age groups and saw that the completion rate was higher for patients that attended suburban clinics when compared to patients that attended urban clinics. But, wait a minute! What’s going to happen to the relationship between age group and completion rate if we were to segregate the analysis by location type 💭? For instance, would there still not be a significant difference between the two age groups? Let’s determine if there are any changes in the completion rate between the two age groups when segregating by location type.</p>
<pre class="r"><code>df %&gt;% 
  group_by(locationtype, agegroup, completed) %&gt;% 
  summarise(count = n()) %&gt;% 
  mutate(percentage = round(count/sum(count), 2)) %&gt;% 
ggplot(., aes(x = agegroup , y = percentage, fill = completed))+
  geom_col()+
  facet_wrap(.~locationtype)+
  scale_y_continuous(labels = percent)+
  geom_text(aes(label = paste0(round(percentage*100),&quot;%\n&quot;, &#39;(&#39;,count,&#39;)&#39;)), position = position_stack(vjust = 0.5))+
  scale_fill_brewer(palette = &quot;Dark2&quot;)+
  labs(y = &quot;HPV vaccine completion rates\n (n)&quot;)</code></pre>
<p><img src="hpv_files/figure-html/unnamed-chunk-2-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>age_location &lt;- df %&gt;% 
  group_by(locationtype, agegroup, completed) %&gt;% 
  summarise(total = n()) %&gt;% 
  spread(completed,total) %&gt;% 
  mutate(total = no + yes) %&gt;% 
  rename(&quot;group&quot; = agegroup, &quot;success&quot; = &quot;yes&quot;) 

#split dataframe by location type then apply prop_test to each section
lapply(split(age_location,age_location[,1]), function(x){
  print(age_location[1,1])
  prop_test(x)
  })</code></pre>
<pre><code>## # A tibble: 1 x 1
##   locationtype
##   &lt;fct&gt;       
## 1 suburban    
## --------------------------------------------------------------------
## Proportion test for: 11-17 vs 18-26
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 18.984, df = 1, p-value = 1.318e-05
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.07541316 0.20328059
## sample estimates:
##    prop 1    prop 2 
## 0.4493827 0.3100358 
## 
## # A tibble: 1 x 1
##   locationtype
##   &lt;fct&gt;       
## 1 suburban    
## --------------------------------------------------------------------
## Proportion test for: 11-17 vs 18-26
##  2-sample test for equality of proportions with continuity
##  correction
## 
## data:  c(x$success[i], x$success[j]) out of c(x$total[i], x$total[j])
## X-squared = 4.6969, df = 1, p-value = 0.03022
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.190904978 -0.006269469
## sample estimates:
##    prop 1    prop 2 
## 0.2195946 0.3181818</code></pre>
<pre><code>## $suburban
## NULL
## 
## $urban
## NULL</code></pre>
<p>It appears that segregating by location type causes the previously observed relationship between age group and completion rate to change 😕. In fact, the completion rate in suburban clinics for the two age groups is the exact opposite of the completion rate in urban clinics. The completion rate for the 11-17 age group is significantly higher than the completion rate of the 18-26 age group in suburban areas (p &lt; 0.05) but interestingly, the completion rate is significantly lower in urban areas for the 11-17 age group (p &lt; 0.05). Based on the bar chart we see that 31% of patients in the 18-26 age group completed the vaccine at suburban clinics while 32% completed the vaccine at urban clinics. However, 45% of patients in the 11-17 age group completed the vaccine at suburban clinics while only 22% completed the vaccine at urban clinics. Thus, the completion rates for the 11-17 age group is affected by the clinic’s location and we can infer that 11 to 17 year old patients attending urban clinics may be at a higher risk for non-completion.</p>
</div>
<div id="logistic-regression" class="section level3">
<h3>Logistic Regression</h3>
<p>Let’s create a logistic regression model to explore the association between the predictors and completion rate. The main purpose here would be to isolate the relationship between the predictors and completion rate from the effects of any confounding variables. For instance, say that the completion rate is higher in suburban clinics and that females between the ages of 11 and 17 were more likely to attend suburban clinics. In this case, as we have seen in the previous section, inferences about the completion rate and age group gets manipulated by the effect of location type on age and completion rate. This strange effect is known as <a href="https://ftp.cs.ucla.edu/pub/stat_ser/r414.pdf">Simpson’s Paradox</a>, a phenomenon in which trends that appear when the data is segregated into groups changes when the the data is aggregated. Thus, we’ll use logistic regression to adjust for this effect and draw more accurate conclusions as to which groups are at a high risk of non-completion.</p>
<pre class="r"><code>#create desired reference groups
var_levels &lt;- c(&quot;18-26&quot;,&quot;minority&quot;,&quot;no insurance&quot;,&quot;urban&quot;,&quot;family practice&quot;)
for (i in seq_along(var_levels)){
  df[[i+1]] &lt;- relevel(df[[i+1]], var_levels[i])
}

#function to create conditional models
conditional_model &lt;- function(filter_vars,model_formula){
  df_filtered &lt;- df %&gt;% 
    filter(eval(parse(text=filter_vars)))
  glm(eval(parse(text=model_formula)),family = binomial, data = df_filtered) %&gt;% 
    #exponentiate results to compute odds
    tidy(conf.int=TRUE, exponentiate = TRUE) %&gt;%
    #remove intercept term
    slice(-1) %&gt;% 
    select(-c(std.error, statistic)) %&gt;% 
    mutate(estimate = round(estimate, 2),
           conf.low = round(conf.low,2),
           conf.high = round(conf.high,2),
           p.value = if_else(p.value &lt; .05, &#39;p-value &lt; 0.05&#39;, &#39;p-value &gt; 0.05&#39;))
}

#create conditional models. The output would not be displayed directly 
#as we&#39;ll use inline code for the values
age26_location &lt;- conditional_model(&quot;agegroup == &#39;18-26&#39;&quot;, &quot;completed~locationtype&quot;)
age17_location &lt;- conditional_model(&quot;agegroup == &#39;11-17&#39;&quot;, &quot;completed~locationtype&quot;)

pediatric_agegroup &lt;- conditional_model(&quot;practicetype == &#39;pediatric&#39;&quot;, &quot;completed~agegroup&quot;)
obgyn_agegroup &lt;- conditional_model(&quot;practicetype == &#39;ob-gyn&#39;&quot;, &quot;completed~agegroup&quot;)
family_agegroup &lt;- conditional_model(&quot;practicetype == &#39;family practice&#39;&quot;, &quot;completed~agegroup&quot;)

pediatric_location &lt;- conditional_model(&quot;practicetype == &#39;pediatric&#39;&quot;, &quot;completed~locationtype&quot;)
obgyn_location &lt;- conditional_model(&quot;practicetype == &#39;ob-gyn&#39;&quot;, &quot;completed~locationtype&quot;)

insurance_location &lt;- conditional_model(&quot;medassist == &#39;insurance&#39;&quot;, &quot;completed~locationtype&quot;)
noinsurance_location &lt;- conditional_model(&quot;medassist == &#39;no insurance&#39;&quot;, &quot;completed~locationtype&quot;)
                                          
insurance_agegroup &lt;- conditional_model(&quot;medassist == &#39;insurance&#39;&quot;, &quot;completed~agegroup&quot;)
noinsurance_agegroup &lt;- conditional_model(&quot;medassist == &#39;no insurance&#39;&quot;, &quot;completed~agegroup&quot;)

white_location &lt;- conditional_model(&quot;race == &#39;white&#39;&quot;, &quot;completed~locationtype&quot;)
minority_location &lt;- conditional_model(&quot;race == &#39;minority&#39;&quot;, &quot;completed~locationtype&quot;)

#full model
glm(completed~., family = binomial, data = df) %&gt;% 
  tidy(conf.int = TRUE,exponentiate = TRUE) %&gt;% 
  select(-c(std.error, statistic)) %&gt;%
  mutate_if(is.numeric, round, 4) %&gt;% 
  slice(-1) %&gt;% 
  rename(&#39;odds ratio (OR)&#39; = estimate) %&gt;% 
  kable(caption = &quot;Multivariate Logistic Regression Output&quot;) %&gt;% 
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Multivariate Logistic Regression Output
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
odds ratio (OR)
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
agegroup11-17
</td>
<td style="text-align:right;">
1.7317
</td>
<td style="text-align:right;">
0.0005
</td>
<td style="text-align:right;">
1.2739
</td>
<td style="text-align:right;">
2.3574
</td>
</tr>
<tr>
<td style="text-align:left;">
racewhite
</td>
<td style="text-align:right;">
1.3864
</td>
<td style="text-align:right;">
0.0062
</td>
<td style="text-align:right;">
1.0977
</td>
<td style="text-align:right;">
1.7525
</td>
</tr>
<tr>
<td style="text-align:left;">
medassistinsurance
</td>
<td style="text-align:right;">
1.9414
</td>
<td style="text-align:right;">
0.0008
</td>
<td style="text-align:right;">
1.3224
</td>
<td style="text-align:right;">
2.8758
</td>
</tr>
<tr>
<td style="text-align:left;">
locationtypesuburban
</td>
<td style="text-align:right;">
1.4869
</td>
<td style="text-align:right;">
0.0144
</td>
<td style="text-align:right;">
1.0840
</td>
<td style="text-align:right;">
2.0472
</td>
</tr>
<tr>
<td style="text-align:left;">
practicetypeob-gyn
</td>
<td style="text-align:right;">
1.7882
</td>
<td style="text-align:right;">
0.0002
</td>
<td style="text-align:right;">
1.3187
</td>
<td style="text-align:right;">
2.4347
</td>
</tr>
<tr>
<td style="text-align:left;">
practicetypepediatric
</td>
<td style="text-align:right;">
1.2584
</td>
<td style="text-align:right;">
0.2327
</td>
<td style="text-align:right;">
0.8634
</td>
<td style="text-align:right;">
1.8378
</td>
</tr>
</tbody>
</table>
<p>Patients aged 11 to 17 years old were 1.73 times more likely to complete the vaccine than 18 to 26 year old patients. This is a direct contradiction of the results we saw form the proportion test between the two age groups, which stated that there was no difference in the completion rates between the two age groups. There was no significant difference in the completion rates among 18 to 26 year old patients in suburban and urban clinics (OR = 0.96, p-value &gt; 0.05, CI = (0.66, 1.42)) but patients aged 11 to 17 were almost three times more likely to complete the vaccination in suburban clinics than urban clinics (OR = 2.9, p-value &lt; 0.05, CI = (2.08, 4.09))</p>
<p>Patients with insurance were 1.94 times more likely to complete the vaccine than patients without insurance. Additionally, for patients with insurance the completion rate in suburban clinics was higher than urban clinics (OR = 1.42, p-value &lt; 0.05, CI = (1.03,1.96)) while there was no difference in the completion rates between suburban and urban locations for patients without insurance (OR = 0.57, p-value &gt; 0.05, CI = (0.19,1.41)). For patients without insurance there was no difference in the completion rate between the two age groups (OR = 1.24, p-value &gt; 0.05, CI = (0.61,2.68)) but 11 to 17 year old patients with insurance were more likely to complete the vaccine than 18 to 26 year old patients with insurance (OR = 1.47, p-value &lt; 0.05, CI = (1.16,1.88)).</p>
<p>In pediatric clinics the completion rate for 11 to 17 year old patients was higher (OR = 3.54, p-value &lt; 0.05, CI = (1.36, 12.07)). In family practice clinics patients aged 11 to 17 were also more likely to complete the vaccine (OR = 1.81, p-value &lt; 0.05, CI = (1.13, 2.89)) while in ob-gyn clinics there was no significant difference in completion rates between the two age groups (OR = 1.43, p-value &gt; 0.05, CI = (0.91, 2.24)). Additionally, we also see that differences in completion rates were associated with location type when segregating by practice type. Pediatric patients that attended suburban clinics were almost four times more like to complete the vaccination when compared to pediatric patients in urban clinics (OR = 3.71, p-value &lt; 0.05, CI = (2.52, 5.5)).This may due to the fact that 93.5% of pediatric patients were between 11 and 17 years of age. However, there were no differences in completion rates between suburban and urban clinics for ob-gyn patients (OR = 1.08, p-value &gt; 0.05, CI = (0.73, 1.6)). Additionally, this sample did not contain any family practice clinics within urban locations so we were unable to draw any inferences about the completion rates between urban and suburban locations for family practice clinics.</p>
<p>White patients were 1.37 times more likely to complete the vaccination when compared to minority patients (Black/Hispanic). Among white patients there was no significant difference in the completion rate between the two location types (OR = 1.38, p-value &gt; 0.05, CI = (0.98, 1.95)). However, the completion rate at suburban clinics was twice as high as the completion rate at urban clinics for minority patients (OR = 2.01, p-value &lt; 0.05, CI = (1.39, 2.93)).</p>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>Through this analysis we determined that the completion rate among patients between the ages of 11 to 17 was significantly affected by the clinic’s location. Specifically, young patients in urban clinics were at a higher risk of non-completion. Additionally, minority patients in urban clinics were also at a high risk of non-completion. Based on these two findings can we further infer that minority patients between 11 and 17 years of age that attend urban clinics are highly unlikely to complete the vaccination in urban clinics?</p>
<p>I’d like to wrap up by stating that my purpose here was not to do a rigorous statistical analysis for an academic paper but instead to shine a 💡 on how fun statistics can be and to show how simple statistical methods and data visualizations can be employed to generate inferences about the population given sample data.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
